id: ID5603BF8
legacy_id: P007038
ocr_import_info:
  bdrc_scan_id: W22141
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T02:47:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:48:14.146937+00:00'
last_modified: 2022-09-02 04:48:49.261568
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22141
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22141
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྣལ་འབྱོར་རྒྱུད་ཀྱི་རྣམ་བཤད་སོགས།
  author: ཀརྨ་པ ༠༨་མི་བསྐྱོད་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.8249159654292347
  ocr_word_median_confidence_index: 0.9200000166893005
quality: null
bases:
  I1657:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1657
      total_pages: 492
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1657.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8430539262817138
    legacy_id: v001
  I1658:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1658
      total_pages: 486
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1658.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8342846997907507
    legacy_id: v002
  I1660:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1660
      total_pages: 330
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1660.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8266660295707243
    legacy_id: v004
  I1659:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1659
      total_pages: 482
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1659.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.7933223759734903
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
