id: ID5603BF8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T02:49:28+00:00'
last_modified: '2022-06-08T13:32:20.388518+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22141
  title: རྣལ་འབྱོར་རྒྱུད་ཀྱི་རྣམ་བཤད་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2BDE:
      image_group_id: I1657
      title: ''
      total_pages: 492
      order: 1
      base_file: 2BDE.txt
    1E3C:
      image_group_id: I1658
      title: ''
      total_pages: 486
      order: 2
      base_file: 1E3C.txt
    F198:
      image_group_id: I1659
      title: ''
      total_pages: 482
      order: 3
      base_file: F198.txt
    552F:
      image_group_id: I1660
      title: ''
      total_pages: 330
      order: 4
      base_file: 552F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
