id: P007038
initial_creation_type: ocr
source_metadata:
  id: bdr:W22141
  title: རྣལ་འབྱོར་རྒྱུད་ཀྱི་རྣམ་བཤད་སོགས
  author: ''
  volumes:
    78c0d63cd1064ee0a3be2d00943e5115:
      image_group_id: I1657
      title: ''
      volume_number: 1
      total_pages: 492
      base_file: v001.txt
    f0e10b8462c84bdca7bacb1bc6dd739f:
      image_group_id: I1658
      title: ''
      volume_number: 2
      total_pages: 486
      base_file: v002.txt
    f69c3ecec95f4b5d974d22500f130f86:
      image_group_id: I1659
      title: ''
      volume_number: 3
      total_pages: 482
      base_file: v003.txt
    e600109f9b7941a58da361ef820bfb72:
      image_group_id: I1660
      title: ''
      volume_number: 4
      total_pages: 330
      base_file: v004.txt
ebook_metadata:
  title: རྣལ་འབྱོར་རྒྱུད་ཀྱི་རྣམ་བཤད་སོགས
  author: ''
  sku: P007038
  cover: cover.jpg
  layers:
  - pagination
